theme: jekyll-theme-architect
title: Welcome to Ram Rahul's personal GitHub AI homepage !
secsription: This is website that I am creating to record the timeline of all the findings and learning that I have done and will be doing to become a Data Scientist.
